apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: eo7vt3pq5-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/eo7vt3pq5-java-springboot-gitops